version: "3"

networks:
  backend:
    driver: bridge

services:
  app:
    build: ./app
    environment:
      - PORT=${PHOENIX_PORT}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POOL_SIZE=${POOL_SIZE}
    volumes:
      - ./app:/usr/src/app
    ports:
      - ${PHOENIX_PORT}:4000
    stdin_open: true
    tty: true
    command:
      sh -c "mix phx.server --no-halt"
    networks:
      - backend

  db:
    build: ./db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db/postgres/tmp/data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
