version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

    working_directory: ~/app

    steps:
      - checkout

      - run: docker system prune --force

      - run:
          name: Confirm directory state
          command: |
            set -x
            pwd && ls
            echo "ls app/my_app"
            ls app/my_app

      - run:
          name: Build Docker container
          command: |
            set -x
            docker-compose build
            docker-compose run --rm app sh -c "mix --version"

      - run:
          name: Mix deps.get
          command: |
            set -x
            docker-compose run --rm app sh -c "pwd && ls && cd my_app && mix deps.clean --all && mix deps.get"

      - run:
          name: Run Docker container
          command: |
            set -x
            docker-compose up -d
            sleep 10
            docker ps -f status=running

      - run:
          name: Mix test
          command: |
            set -x
            docker-compose run --rm app sh -c "pwd && ls && cd my_app && mix test"

      # - run:
      #     name: Direct run Docker container and Confirm mix test
      #     command: |
      #       set -x
      #       docker-compose run --rm app sh -c "mix --version & mix test"

      # - run:
      #     name: mix
      #     command: docker-compose exec app mix archive

      - run: docker-compose down

      - run:
          name: Finish message
          command: echo "finish build."
