version: 2.1
jobs:
  build:
    docker:
      - image: circleci/elixir:1.10.4
        environment:
          MIX_ENV: test
    steps:
      - checkout

      - run:
          name: Install Hex
          command: mix local.hex --force

      - run:
          name: Install Rebar
          command: mix local.rebar --force

      - run:
          name: Mix deps.get
          command: mix deps.get

      - run:
          name: Mix compile
          command: mix compile

      - run:
          name: Check format
          command: mix format --check-formatted

      - run:
          name: Running mix test
          command: mix test

      - run:
          name: Finish build
          command: echo "finish build"
