version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

    working_directory: ~/app

    steps:
      - checkout

      - run: docker system prune
      - run:
          name: Build and Run Docker
          command: |
            set -x
            docker-compose build
            docker-compose up -d
            docker-compose run --rm app bash -c "mix local.hex && mix --version"

      # - run:
      #     name: Run Docker container
      #     command: |
      #       set -x
      #       docker-compose up -d
      #       mix test

      # - run:
      #     name: Mix test
      #     command: |
      #       docker-compose exec app bash -c "cd my_app && mix test"

      # - run:
      #     name: mix
      #     command: docker-compose exec app mix archive

      - run:
          name: Finish message
          command: echo "finish build."
