version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-1604:202010-01

jobs:
  build:
    executor:
      name: machine-executor
    steps:
      - checkout
      - run:
          name: Build Docker containers
          command: |
            set -x
            docker-compose build
            docker-compose run --rm app bash -c "mix --version && mix archive && node --version && npm --version"
            docker-compose run --rm db psql --version
      - run:
          name: Mix deps.get & compile
          command: |
            set -x
            docker-compose run --rm app bash -c "ls && mix deps.get && mix deps.compile"
      - run:
          name: Check directories and existed mix dependencies
          command: |
            set -x
            pwd && ls -a && ls -a app && ls app/deps
            docker-compose run --rm app mix deps
      - run:
          name: Npm install in assets directory
          command: |
            set -x
            docker-compose run --rm app bash -c "cd assets && ls && npm i && node node_modules/webpack/bin/webpack.js --mode development"
      - run:
          name: Run Docker containers
          command: |
            set -x
            docker-compose up -d
            sleep 5
            docker ps -f status=running
            docker-compose logs
      - run:
          name: Mix format
          command: |
            set -x
            docker-compose exec app mix format --check-formatted
      - run:
          name: Mix test
          command: |
            set -x
            docker-compose exec app bash -c "MIX_ENV=test mix test"
      - run:
          name: Finish build pipeline
          command: |
            set -x
            echo "Finish pipeline"
