version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - checkout

      - run:
          name: Confirm directory state
          command: |
            set -x
            pwd && ls
            echo "ls app/my_app"
            ls app/my_app

      - run:
          name: Build Docker container
          command: |
            set -x
            docker-compose build
            docker-compose run --rm app sh -c "mix --version"

      - run:
          name: Mix deps.get
          command: |
            set -x
            docker-compose run --rm app sh -c "pwd && ls && cd my_app && mix deps.clean --all && mix deps.get"

      - run:
          name: Npm install in assets directory
          command: |
            set -x
            docker-compose run --rm app sh -c "pwd && ls && cd my_app/assets && npm install"

      # - run:
      #     name: Run Docker container
      #     command: |
      #       set -x
      #       docker-compose up -d
      #       sleep 10
      #       docker ps -f status=running
      #       docker-compose logs

      - run:
          name: Confirm exist mix archive
          command: |
            set -x
            docker-compose run --rm app sh -c "pwd && ls && cd my_app && mix archive"

      - run:
          name: Mix test
          command: |
            set -x
            docker-compose run --rm app sh -c "pwd && ls && cd my_app && mix test"
            docker-compose up

      - run:
          name: Down Docker container and Finish pipeline
          command: |
            set -x
            docker-compose down
            echo "Finish pipeline"
