version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Build Docker
          command: |
            set -x
            docker-compose build

      - run:
          name: mix test
          command: |
            docker-compose run --rm app bash -c "cd my_app && mix test"

      - run:
          name: Run Docker container
          command: |
            set -x
            docker-compose up -d
            mix test

      # - run:
      #     name: mix
      #     command: docker-compose exec app mix archive

      - run:
          name: Finish message
          command: echo "finish build."
