version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

    working_directory: ~/app

    steps:
      - checkout

      - run: docker system prune --force
      - run:
          name: Confirm directory state
          command: |
            pwd && ls
            echo "ls app/"
            ls app/

      - run:
          name: Build and Run Docker container
          command: |
            set -x
            docker-compose build
            docker-compose up -d

      - run:
          name: Direct run Docker container and Confirm mix test
          command: |
            set -x
            docker-compose run --rm app sh -c "mix --version & mix test"

      # - run:
      #     name: Mix test
      #     command: |
      #       docker-compose exec app bash -c "cd my_app && mix test"

      # - run:
      #     name: mix
      #     command: docker-compose exec app mix archive

      - run:
          name: Finish message
          command: echo "finish build."
